test('Test the tester', () => {
  throw new Error('on purpose')
})